server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  output:
    ansi:
      enabled: always

  application:
    name: ViVuMate

  profiles:
    active: dev

  messages:
    basename: i18n/messages
    encoding: UTF-8

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  mail:
    #    host: smtp.gmail.com
    host: smtp.resend.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  docker:
    compose:
      enabled: false
      file: docker-compose.yml

vivumate:
  weather:
    api-key: ${OPENWEATHER_API_KEY}
    base-url: https://api.openweathermap.org/data/2.5/weather

  jwt:
    secret-key: ${JWT_SECRET_KEY}
    refreshKey: ${JWT_REFRESH_KEY}
    resetKey: ${JWT_RESET_KEY}
    verifyKey: ${JWT_VERIFY_KEY}

    access:
      expiration: 1800000 # 30 phút
    refresh:
      expiration: 604800000 # 7 ngày
    reset:
      expiration: 300000 # 5 phút
    verify:
      expiration: 900000 # 15 phút
    otp-login:
      expiration: 300000 # 5 phút

  app:
    frontend-url: ${FRONTEND_URL:http://localhost:3000}

  openapi:
    dev-url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
